### ISSUE TITLE
Expand the Contributing Section

### ISSUE THREAD

**Issue by gondolyr** [TrevorSatori/kronos#15]
At the time of writing, I am not sure what steps to take to be able to contribute back to your project. Things such as commit style (such as using [Conventional Commits](https://www.conventionalcommits.org/) or another style), code style (use rustfmt?), issue formats/templates, and more are things newcomers have to make assumptions about.

_Aside_: I'm in favor of supporting Conventional Commits because it enables the use of tools like [git-cliff](https://github.com/orhun/git-cliff) or [git-chglog](https://github.com/git-chglog/git-chglog) to generate changelogs.

Having a `CONTRIBUTING.md` file can help encourage others to contribute by listing the ways people can help the project. It can also provide project guidelines such as commit style, code style, how to write feature requests or bugs, etc. The [https://contributing.md website](https://contributing.md/how-to-build-contributing-md/) can be a good starting place for one.

I would especially appreciate a section dedicated to commit styles, especially around writing descriptive commit messages. The history of this project is challenging to read through based on the messages alone and without going into each commit to see what was done. On top of that, many of the commits don't elaborate _why_ they are being added (we can't read your mind :slightly_smiling_face:). 

Below are some resources I like to point others to for commit messages:
  * https://cbea.ms/git-commit/
  * https://dhwthompson.com/2019/my-favourite-git-commit

**Comment by TrevorSatori** [comment]
Hey Gondolyr, thanks for taking the time to check out, fork the project and reach out. Everything you're saying is valid & I will work on getting a Contributing.md up within the next few days. Will wait to close the problem until that's done.
