### ISSUE TITLE
Add support for Ogg Vorbis

### ISSUE THREAD

**Issue by willi-kappler** [TrevorSatori/kronos#16]
The underlying crates support the ogg vorbis format but the ReadMe doesn't mention it.
(Unless of course if the format is really not supported it should be added.)

**Comment by TrevorSatori** [comment]
Hey, thanks for reaching out. After testing, I've added support for ogg files. Good catch!

**Comment by willi-kappler** [comment]
That's really nice, thanks for fixing it!
