### ISSUE TITLE
Audio doesn't sound as good as other media players

### ISSUE THREAD

**Issue by gondolyr** [TrevorSatori/kronos#19]
This is highly subjective, however, when I listen to the same track with other media players like [mpv](https://mpv.io/), they sound better than the backend kronos is using.

I'm using Pop!_OS 22.04, which defaults to PipeWire. I noticed that when I'm using kronos, it is using ALSA, though I'm not sure if this is what's causing this difference I'm hearing. It's also possible that mpv is using an equilizer by default. Perhaps this can be remedied with an equilizer in the future.

For now, I wanted to document this discrepency I noticed and will continue to investigate.

**Comment by gondolyr** [comment]
I'd have to experiment with this but [Symphonia](https://docs.rs/symphonia/latest/symphonia/) could be a good replacement for the `rodio` library if there's an issue in it. [termusic](https://github.com/tramhao/termusic) uses it.

**Comment by TrevorSatori** [comment]
After a bit of thought I believe this perceived quality is from the crates others are using, specifically FFMPEG. I specifically wanted to avoid using this to minimize dependencies needed, not sure of further action to be done.
