### ISSUE TITLE
Panic whilst attempting to play mp3 file

### ISSUE THREAD

**Issue by Luxzi** [TrevorSatori/kronos#33]
**Operating system**:  NixOS unstable
**Kronos version (commit hash)**: `128f5c2`

I was attempting to create a Nix flake for Kronos, but when I hit play on any file, the program paniced with the message:

```rust
thread 'main' paniced at src/helpers/gen_funcs.rs:19:42: called `Option::unwrap()` on `None` value
```
I then tried to compile Kronos manually with `cargo build --release` but it gave  the same result. I'm unsure as to why this is happening since I have all required libraries installed.

See PR #34 for Nix flake.

**Comment by msandoval** [comment]
I had the same problem on one particular music file. I submitted the fix here: [#35](https://github.com/TrevorSatori/kronos/pull/35)
